### ISSUE TITLE
nodeSql error functions are being called twice

### ISSUE THREAD

**Issue by holtjonathan** [moshekarmel1/node-sql#1] opened 2017-05-03 15:50 UTC
Hello, I am noticing a problem when I am calling a SQL proc and it errors.  For instance, let's say that my proc 'BooksInsert' expects 5 params but I only provide 4...I would expect an error to be thrown.  If I call the following code:

`nodeSql.sproc('GLIWeb.dbo.BooksInsert', req.body, config, function(err, result){`
            ` if (err) {`
                 `console.log('I have an error', err);`
                ` return res.status(500).send(err);`
           `  }`
           `  else {`
                ` console.log('i do not have an error', err);`
            `     res.status(201).json(result);`
           `  }`
`})`
nodeSql is running through the callback with err = NULL (thus hitting "i do not have an error" section) and then it immediately runs again but this time err is not NULL so it gets into the "I have an error" section.  However, since the response status has already been set (because of the initial runthrough), node is now throwing the "Cant set headers after they are sent" error.

Am I missing something?  Why is nodeSql running this twice (once without an error and then another time with an error)?

**Comment by moshekarmel1** [comment] 2017-05-03 16:11
Hmm... That's strange, I've been using this in various environments for a while w/o any issue. Is it possible that you are calling the endpoint twice? 

Also, I have run into the `Cant set headers after they are sent` error many times in express for various strange reasons in situations when I am trying to return 500 when there is an error. 

Can you try this...

Add this function in the top of your server.js

```
app.use(function(err, req, res, next) {
  // Only handle `next(err)` calls
  if(err){
    res.status(500).json(err);
  }
});
```

Then in your calling function try this ...

```
app.post('api/...', function(req, res, next){
  nodeSql.sproc('GLIWeb.dbo.BooksInsert', req.body, config, function(err, result){
    if (err) {
      console.log('I have an error', err);
      return next(err);
    }
    else {
      console.log('i do not have an error', err);
      res.status(201).json(result);
    }
  })
})
```

**Comment by holtjonathan** [comment] 2017-05-03 16:22
I have already checked about calling it twice and I can see that I am only making the call once.  However, even if I was calling it twice, the `req.body` is the same in both calls and thus the parameter is missing on both calls.  So `err` should be populated both times.

I will definitely give your suggestion a try.  I'll let you know how it goes later today.

Thanks for the quick reply!

**Comment by holtjonathan** [comment] 2017-05-03 16:26
If I comment out the `res.status(201).json(result)` line, my code works as expected.  

Meaning, I get a 500 status with the `err` json message saying `Procedure 'BooksInsert' expects parameter '@Title', which was not supplied`.  This means that I do not send the status when there truly is no error, I just commented out that line as a test to see what happens.  :-)

**Comment by moshekarmel1** [comment] 2017-05-03 16:28
Are you actually seeing 2 inserts in the database in a non-error situation?

**Comment by holtjonathan** [comment] 2017-05-03 16:28
No, I am only seeing one.

**Comment by moshekarmel1** [comment] 2017-05-03 16:30
Yup it's a bug, pretty sure that this line is the issue...

https://github.com/moshekarmel1/node-sql/blob/master/index.js#L85

I need to `return done(_err, null)`

**Comment by moshekarmel1** [comment] 2017-05-03 16:32
Gimme some time to get the fix in, test it, and push to npm.

**Comment by holtjonathan** [comment] 2017-05-03 16:40
Awesome!  Thanks for following up and looking into it man!

**Comment by holtjonathan** [comment] 2017-05-03 16:42
Btw, I am loving this library.  It made connecting Node to SQL a breeze.

**Comment by moshekarmel1** [comment] 2017-05-03 16:45
Yup I was surprised noone had done this yet...

Also, in the meantime, you can make the fix yourself.

Go to `YourProject\node_modules\node-sql\index.js`

On line 85-87 change this 

```
if (_err) {
    done(_err, null);
    return;
}
```

to this

```
if (_err) {
    return done(_err, null);
}
```

**Comment by holtjonathan** [comment] 2017-05-03 17:03
I changed the code in my local node_modules but I am still getting 'double' call and the errors.

**Comment by moshekarmel1** [comment] 2017-05-03 17:17
OK I'll look into it some more.

**Comment by holtjonathan** [comment] 2017-05-03 19:50
I changed my code to be like

```
nodeSql.sproc('GLIWeb.dbo.BooksInsert', req.body, config, function(err, result){
    console.log('req.body.title', req.body);
        if (!req.body.title){
            console.log('missing title');
            res.status(400);
            res.send('Title is required');
        }
        else{
            console.log('good to go');
            res.status(201);
            res.send(result);
        }

```
If I include all params, the `Good to go` section is called and a new record is added.

If I exclude the `Title` param, the `Missing Title` section is called twice.  It seems like it is called once as if there are no problems and then once more when the `BooksInsert` proc returns an error.

**Comment by holtjonathan** [comment] 2017-05-03 20:17
Sorry to spam this issue...I figured that I would change my example to an actual working one :-)

```
if (!req.body.title){
    res.status(400);
    res.send('Title is required');
}
else{
    nodeSql.sproc('GLIWeb.dbo.BooksInsert', req.body, config, function(err, result){
        if (err) {
            console.log('I have an error with the proc');
            res.status(400);
            res.send(err);
        }
        else{
            console.log('I have no errors with the proc');
            res.status(201);
            res.send(result);
        }
    });
}
```

I have changed it so that if the `Title` is missing then I don't even bother calling `BooksInsert`.  But if the proc throws an error (say that I pass a varchar value in a bit field) then the `I have no errors with the proc` section is called and immediately afterwards the `I have an error with the proc` section is called.

**Comment by moshekarmel1** [comment] 2017-05-11 15:20
@holtjonathan I looked into this a bit, and I think I found the issue.

Essentially, the `DoneProc` event, is fired before the Error event. Meaning the sequence is like this:

1. Stored Proc finishes execution (node-sql returns with no error)
2. Error callback fires (node-sql returns with an error)

To fix this, I need to be able to tell on this line : 

https://github.com/moshekarmel1/node-sql/blob/master/index.js#L107
```
request.on('doneProc', function(rowCount, more) {
  done(null, result);
});
```

If there was an error or not. I gotta dig through the tedious documentation to figure out how to tell that.
```
request.on('doneProc', function(rowCount, more) {
  if(!err) done(null, result);
});
```

**Comment by moshekarmel1** [comment] 2017-05-14 17:42
@holtjonathan my most recent commit should address the issue that you've been seeing.

https://github.com/moshekarmel1/node-sql/commit/c03c9fd1656a8329870b33274667f982bbdd6a44

Can you upgrade via npm to version 1.1.3, and let me know if this solves the issue?

Essentially I added a check for a successful call before running the success callback.

**Comment by moshekarmel1** [comment] 2017-05-16 19:13
@holtjonathan I'm pretty sure the issue is fixed now, so I'm going to close it. Feel free to reopen the issue if things are still broken.

**Closed as completed** 2017-05-16 19:14 UTC
Labels: bug
